# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151027132918 on 2015-10-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='date bought')),
                ('maturity_date', models.DateTimeField(verbose_name='maturity')),
                ('notional', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
    ]
