# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151027132918 on 2015-10-28 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeDescription',
            new_name='Trade',
        ),
    ]
